server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_backendManagement?timezone=UTC-8
    username: root
    password: aiqilincs4612
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    port: 6379
    host: localhost




mybatis:
  configuration:
#    开启驼峰命名和下划线命名转换
    map-underscore-to-camel-case: true





