server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_backendManagement?timezone=UTC-8
    username: root
    password: aiqilincs4612
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
#    开启驼峰命名和下划线命名转换
    map-underscore-to-camel-case: true



